### ISSUE TITLE
Pcb routing errors??

### ISSUE THREAD

**Issue by n9jcv** [vonkonow/LEET-Modular#1]
Hello, 

First let me say Thank You for all the hard work and sharing this great collection.

On your site I saw this comment;
"There is a routing error in my PCB design, so three wires need to be adjusted in the current version."

Can you tell me what the errors are so that I can fix them when I build or I can try to fix in the pcb.

Thanks

**Comment by vonkonow** [comment]
![adapter close](https://user-images.githubusercontent.com/67822022/183689836-fd884cdb-dcaa-4ebe-80c5-d03fbe0c45ff.jpg)
here is a rendering of the adaptor I made to solve the routing error for longan nano 1.0 boards (back) and 1.1 boards (front)

**Comment by n9jcv** [comment]
Is the schematic correcthere or on your site?

**Comment by vonkonow** [comment]
The schematic is the same here and on the site, showing how the routing should be. 
For example TFT_DC  shall go to PA11 (not to PA12 as in the gerber)
