### ISSUE TITLE
Programming Help

### ISSUE THREAD

**Issue by ehisforadam** [vonkonow/LEET-Modular#2]
I'm not really familiar with how programming works for this type of board. I have done Arduino, but I am a bit over my head here. I have seen examples for this board that include a platformio.ini file. Visuaual studio also doesn't seem to want to open or import the files off this Github page unless I rename main.cpp to main.ino, then I can import it as an Ardunino project. It seems to load everything, but when I got to compile it I get this error: 
C:/Users/Adam/Documents/PlatformIO/Projects/230207-192426-sipeed-longan-nano/src/main.ino: In function 'void OnTimer()':
C:/Users/Adam/Documents/PlatformIO/Projects/230207-192426-sipeed-longan-nano/src/main.ino:589:17: error: request for member 'delay' in 'delay', which is of non-class type 'void(long unsigned int)'
  589 |     tmp = delay.delay(ADC.anRaw[0], ADC.anAvg[4], ADC.anAvg[3]); // sample, mix, length

**Comment by vonkonow** [comment]
Hi
I used Platform IO in visual studio code. In theory it is possible to use Arduino IDE, but I haven’t tried, and I don’t know if programming would work. Unfortunately, It is a bit tricky to program the first time, hopefully it is better today, but I remember spending some time googling, downloading and installing different USB drivers...
Hope it helps, good luck!

**Comment by ehisforadam** [comment]
Maybe I wasn't being clear. I am using Platformio and I was able to get examples and other code loaded onto the Longan board. The trouble I was having was getting the LEET modular code to be loaded correctly into Platformio. I was able to get Platformio to load it in by changing main to *.ino 
I got that error within Platformio when compiling.

**Comment by vonkonow** [comment]
I didnt use arduino as framework in platform io. Here is the ini file I used:
[env:sipeed-longan-nano]
platform = gd32v
board = sipeed-longan-nano
framework = gd32vf103-sdk
upload_protocol = dfu

**Comment by ehisforadam** [comment]
Oh, I see, the platform in the ini file was messing things up. I am still getting a lot of errors when I try to compile it.
I put the ini file in the scr_generic folder with the scr folder. I was able to load it into Platformio, but I am still getting a bunch of errors when I try to compile it. 

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/gd32v/sipeed-longan-nano.html
PLATFORM: GigaDevice GD32V (1.3.0) > Sipeed Longan Nano
HARDWARE: GD32VF103CBT6 108MHz, 32KB RAM, 128KB Flash
DEBUG: Current (altera-usb-blaster) External (altera-usb-blaster, gd-link, jlink, rv-link, sipeed-rv-debugger, um232h)
PACKAGES:
 - framework-gd32vf103-sdk @ 1.0.0
 - tool-dfuutil @ 1.9.200310
 - toolchain-gd32v @ 9.2.0
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 0 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio\build\sipeed-longan-nano\src\data\font.o
Compiling .pio\build\sipeed-longan-nano\src\data\frequency.o
Compiling .pio\build\sipeed-longan-nano\src\data\images.o   
Compiling .pio\build\sipeed-longan-nano\src\drivers\SysTick.o
Compiling .pio\build\sipeed-longan-nano\src\drivers\adc.o    
Compiling .pio\build\sipeed-longan-nano\src\drivers\display.o
Compiling .pio\build\sipeed-longan-nano\src\drivers\encoder.o
Compiling .pio\build\sipeed-longan-nano\src\drivers\scope.o
Compiling .pio\build\sipeed-longan-nano\src\drivers\spi.o
Compiling .pio\build\sipeed-longan-nano\src\drivers\timer.o
In file included from src\data\font.cpp:3:
C:\Users\Adam\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_standard_peripheral/gd32vf103.h:179:41: error: redeclaration of C++ built-in type 'bool' [-fpermissive]
  179 | typedef enum {FALSE = 0, TRUE = !FALSE} bool;
      |                                         ^~~~
Compiling .pio\build\sipeed-longan-nano\src\drivers\usbfs\drv_usb_core.o
Compiling .pio\build\sipeed-longan-nano\src\drivers\usbfs\drv_usb_dev.o
In file included from src\data\frequency.cpp:3:
C:\Users\Adam\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_standard_peripheral/gd32vf103.h:179:41: error: redeclaration of C++ built-in type 'bool' [-fpermissive]
  179 | typedef enum {FALSE = 0, TRUE = !FALSE} bool;
      |                                         ^~~~
In file included from src\data\images.cpp:3:
C:\Users\Adam\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_standard_peripheral/gd32vf103.h:179:41: error: redeclaration of C++ built-in type 'bool' [-fpermissive]
  179 | typedef enum {FALSE = 0, TRUE = !FALSE} bool;
      |                                         ^~~~
In file included from src\drivers\SysTick.cpp:2:
C:\Users\Adam\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_standard_peripheral/gd32vf103.h:179:41: error: redeclaration of C++ built-in type 'bool' [-fpermissive]
  179 | typedef enum {FALSE = 0, TRUE = !FALSE} bool;
      |                                         ^~~~
*** [.pio\build\sipeed-longan-nano\src\data\font.o] Error 1
In file included from src\drivers\adc.h:5,
                 from src\drivers\adc.cpp:1:
C:\Users\Adam\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_standard_peripheral/gd32vf103.h:179:41: error: redeclaration of C++ built-in type 'bool' [-fpermissive]
  179 | typedef enum {FALSE = 0, TRUE = !FALSE} bool;
      |                                         ^~~~
*** [.pio\build\sipeed-longan-nano\src\drivers\SysTick.o] Error 1
*** [.pio\build\sipeed-longan-nano\src\data\images.o] Error 1
*** [.pio\build\sipeed-longan-nano\src\data\frequency.o] Error 1
In file included from src\drivers\encoder.cpp:3:
C:\Users\Adam\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_standard_peripheral/gd32vf103.h:179:41: error: redeclaration of C++ built-in type 'bool' [-fpermissive]
  179 | typedef enum {FALSE = 0, TRUE = !FALSE} bool;
      |                                         ^~~~
*** [.pio\build\sipeed-longan-nano\src\drivers\adc.o] Error 1
In file included from src\drivers\display.cpp:7:
C:\Users\Adam\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_standard_peripheral/gd32vf103.h:179:41: error: redeclaration of C++ built-in type 'bool' [-fpermissive]
  179 | typedef enum {FALSE = 0, TRUE = !FALSE} bool;
      |                                         ^~~~
In file included from src\drivers\timer.cpp:3:
C:\Users\Adam\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_standard_peripheral/gd32vf103.h:179:41: error: redeclaration of C++ built-in type 'bool' [-fpermissive]
  179 | typedef enum {FALSE = 0, TRUE = !FALSE} bool;
      |                                         ^~~~
*** [.pio\build\sipeed-longan-nano\src\drivers\encoder.o] Error 1
src\drivers\usbfs\drv_usb_dev.c: In function 'usb_devcore_init':
src\drivers\usbfs\drv_usb_dev.c:80:17: warning: unused variable 'ram_addr' [-Wunused-variable]
   80 |     uint32_t i, ram_addr = 0;
      |                 ^~~~~~~~
src\drivers\usbfs\drv_usb_core.c: In function 'usb_txfifo_write':
src\drivers\usbfs\drv_usb_core.c:251:9: warning: 'packed' attribute ignored for type 'uint32_t *' {aka 'long unsigned int *'} [-Wattributes]     
  251 |         *fifo = *((__packed uint32_t *)src_buf);
      |         ^
src\drivers\usbfs\drv_usb_core.c: In function 'usb_rxfifo_read':
src\drivers\usbfs\drv_usb_core.c:274:9: warning: 'packed' attribute ignored for type 'uint32_t *' {aka 'long unsigned int *'} [-Wattributes]     
  274 |         *(__packed uint32_t *)dest_buf = *fifo;
      |         ^
In file included from src\drivers\spi.cpp:2:
C:\Users\Adam\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_standard_peripheral/gd32vf103.h:179:41: error: redeclaration of C++ built-in type 'bool' [-fpermissive]
  179 | typedef enum {FALSE = 0, TRUE = !FALSE} bool;
      |                                         ^~~~
*** [.pio\build\sipeed-longan-nano\src\drivers\timer.o] Error 1
*** [.pio\build\sipeed-longan-nano\src\drivers\display.o] Error 1
*** [.pio\build\sipeed-longan-nano\src\drivers\spi.o] Error 1
========================================================== [FAILED] Took 1.29 seconds ==========================================================

**Comment by ehisforadam** [comment]
This seems to be a topic related to this error I am getting, but I don't really know what it means: https://github.com/riscv-mcu/GD32VF103_Firmware_Library/pull/3

**Comment by ehisforadam** [comment]
Oh hey, I think I got it to work. I had to replace the gd32vf103.h in the firmware folder and it compiled okay. Now to build the module up and see if she works. 
File location: C:\Users\Adam\.platformio\packages\framework-gd32vf103-sdk\GD32VF103_standard_peripheral  
New file: https://github.com/riscv-mcu/GD32VF103_Firmware_Library/blob/master/Firmware/GD32VF103_standard_peripheral/gd32vf103.h

**Comment by ehisforadam** [comment]
Everything is together and working!

**Comment by vonkonow** [comment]
Now that you mention it, I recall that I did the same procedure years ago. Strange that they still haven’t fixed it...
Anyway, glad that you got it working – well done :)
